language: php

php:
  - 7.0

before_script:
  - travis_retry composer self-update

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover